main.ui
pmps.py

After change from small values to ginormous ones the data was no longer fitting the UI space so the only reasonable approach was to make the labels vertical.

ENH: Rotated label for evRangeCnst

---

preemptive_requests.py
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui

As requested by @slacAWallace:
- Change Entry ID to Assertion ID
- Modify PV for Active status
- Add rule to ensure that only Active preemptive requests are visible.
Creating PR as draft until I can test it at one of the `console` machines with all the proper PVs.

Preemptive Request Tab updates

---

templates/fastfaults_entry.ui
templates/fastfaults_header.ui

In order to make the text readable without exploding in screen size scrollAreas were added to variable name and to Description along with wordWrap.
WordWrap works perfectly for the description as it has spaces but the variable name is a string without spaces so it has no effect.
This is how it looks now:

ENH: ScrollArea and WordWrap for FF Text

---

KFE_config.yml
LFE_config.yml

This issue was reported by @slacAWallace and it seems to have showed up after upgrade of Grafana to 7.1.
This is how it renders without this patch:
And this is how it renders with the patch in place:
Looking at the changelogs, I noticed that a fixed issue is very similar to what we are seeing: https://github.com/grafana/grafana/issues/26442. While this issue talks about iOS, our embedded webbrowser can also be suffering from the same issue. The fix for this issue was released with 7.1.1...
I put a message for PCDS IT to look into the possibility to upgrade Grafana to a newer version including the bugfixes released.
This PR is just a workaround so users can at least see something I will update the URL to remove the filters on panel and display the whole page. Better somewhat properly …

FIX: Workaround to at least be able to render something at the Grafana viewer.

---

ev_calculation.py
ev_calculation.ui
pmps.py
pmps.ui
widgets.py

This PR adds two new widgets to the PMPS-UI:
- UndulatorWidget: a representation of a single undulator as a rectangular drawing following the specifications provided by Alex in this [Confluence Page](https://confluence.slac.stanford.edu/pages/viewpage.action?spaceKey=L2SI&title=PMPS+Operator+Interface#PMPSOperatorInterface-eVCalculation).
- UndulatorListWidget: Based on the First and Last segment PVs for a given line, it generates a list of UndulatorWidgets along with the undulator number and Current/Target K values.
The widgets were added into the the ev_calculation.py file that is used by pmps.py to add it into the proper Tab.
Attn. @slacAWallace

ENH: Add eV Calculation tab and widgets for undulator graphical representation.

---

widgets.py

Looks like the undulators can go over the upper and lower K values! 🤯 
This PR is ready to go pending @slacAWallace confirmation of the values. Initially was 0-10 but maybe it is 0-6... who knows?

FIX: Use hardcoded values for the horizontal scale of undulator widgets.

---

widgets.py

Closes #22 
Contents of this PR:
- Fixes the issue in which after a reconnection of the IOC the widget would render again the undulators.
- Reduce the size of the bar
- Adds limits rendering to the bars for better visualization of the graphical representation.
Screenshot:

Fixes and Enhancements for eV Calculation Tab

---

pmps.ui

This needs to be tested again to make sure I did not change anything that I was not supposed to....  but this is kind of how it looks now:
Please let me know if I should change anything about this. 
We could expend the `Requested Beam Parameters` and the `ev`  - but I am not sure if it will look better, maybe in the empty part on top of the screen now we can add more info?
Trying to close #27

Move Grafana Log Display to a tab

---

pmps.py
pmps.ui

Trying to close #33 & close #29 - since they are both little ones I put them together. 
Here is what the Line indicator looks like now, but we can move this anywhere where we find it to be more appropriate - maybe in the description of the PyDM window itself? I'm open for suggestions here, also I added some color to it but if we find it distracting I can remove that, same thing with the additional str: `Line: ` I can get rid of it and only have `KFE` or `LFE` displayed.

Rename requested beam parameters

---

pmps.ui
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui

- Removed the pulse energy field from the main window from the `Beam Parameter Status`
- Removed the pulse energy field from the preemptive requests tab.
Partially addressing #28 
#36 is removing the third (and I think last) pulse energy field from the whole ui.
I think there are only 3 locations on the ui where we have `pulse energy`

MNT: remove some pulse energy fields

---

line_beam_parameters.py
line_beam_parameters.ui
pmps.py
pmps.ui
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui

Three main changes:
- At the top, the three bitmasks needed to be extended
- In the preemptive request tab, each line's bitmask needed to be extended. This tab uses fixed widths so those were adjusted as well.
- In the line beam parameters control, the number of available bits had to be doubled.
Main confounding factor: EPICS Long types are 32 bit signed integers. So something like "all ones" or `FFFFFFFF` comes through as `-1`, which shows up as empty on the pydm bit indicator.
This PR uses a quick hack to edit the pydm behavior, though this should go to pydm as a feature instead, and it also edits the processing used in the line beam parameter controls.

ENH: update all 16bit eV indicators to 32bit

---

TST_config.yml
fast_faults.py
fast_faults.ui
pmps.py
templates/fastfaults_entry.ui
templates/fastfaults_header.ui

Continuation of #24
Current look at 1366x768, which is my laptop resolution. Note how the var name and desc fields collapse to make room for the larger datetime widgets:

ENH: Datetime continuation

---

KFE_config.yml
fast_faults.ui
line_beam_parameters.ui
templates/fastfaults_header.ui

- Update TMO VAC's config to the new prefix
- Remove the confirm dialog on the line beam parameter control (closes #46)
- Add a datetime widget that shows the arbiter's current time
- Fine adjustments of the layouts for aesthetic lineup

ENH: Small Updates

---

KFE_config.yml
data_bounds.py
fast_faults.py
fast_faults.ui
line_beam_parameters.py
line_beam_parameters.ui
plc_ioc_status.py
plc_ioc_status.ui
pmps.py
preemptive_requests.py
templates/preemptive_requests_entry.ui

- Committed live configuration changes several times (I don't think these config files belong in the repo... there is some refactoring opportunities with the config files and with installing the launcher into the main conda environment)
- Only open the Grafana web page when the tab is opened, and close it when the tab is closed. This helps with the memory management a bit (I think), and it stops us from seeing the javascript errors when not using the grafana logs.
- Compatibility with pydm=1.11.1 rules enum handling (note: will probably need to revert this commit in a follow-up PR after the next PyDM tag, or flip an option or osmething)
- Add a "zero-rate" button to the line beam parameters tab that kills the beam ASAP
- Instead of showing an "Invalid" PV at 0 cycle counts for unused …

ENH: Many fixes and features

---

fast_faults.ui

Functionally, apply a "only show faults that are not OK" filter on first load.
This results in a marginal speedup on startup because we don't do some of the initial rendering etc. on fast faults that aren't going to be shown anyway after the user inevitably applies a filter.
The first time a particular fault shows up can still be slow.
"OK: False" was picked over "Beam Permitted: False" because it'll show things like bypasses.

ENH: start with a simple not-ok filter to speed up initial rendering

---

line_beam_parameters.ui

Slight modification to the readbacks added to the line beam parameters tab in #63
It seems like these were actually pointing to the global readbacks for rate and transmission, rather than to the line beam parameter setting readbacks. These are often exactly the same but sometimes they are not which can lead to some confusion.
No changes to the layout etc. introduced in the previous PR.
Original jira: https://jira.slac.stanford.edu/browse/LCLSECSD-412
closes #69 which was originally observed by Maggie

FIX: use the beam ctrl rbv PVs instead of the global PVs

---

fast_faults.ui

In #68 I opted to start the GUI with a "not OK" filter, but this was a mistake because it misses fast faults that are active and ready to be acknowledged and cleared.
This PR starts with a "no beam" filter, which is the most common use of this screen.
Overall this has the same performance impact as the other PR: initial startup has no gap between "I see the screen" and "I can click buttons", but the process of getting to seeing the screen is still slow.

ENH: switch default filter to no beam instead of not ok

---

arbiter_outputs.py
arbiter_outputs.ui
templates/arbiter_outputs_entry.ui
templates/arbiter_outputs_header.ui

- Move the arbiter output status from the far right over to the left, next to the PV name for easier scanning
- Nitpick alignment of header text
- Fix vertical clipping issue
- closes #54
Before:
After:

ENH: clean up the arbiter output page layout

---

grafana_log_display.py
grafana_log_display.ui
launch.sh
pmps.py
pmps.ui

Currently in live we have a bunch of hotfixes in place to make sure QWeb stuff doesn't load because it causes segfaults when run locally on operator consoles.
Aside from that, we've periodically had issues with the embedded grafana display features. (It doesn't actually display the web page right now which is an issue for another day...). In the past it has crashed the ui for example, which is why we don't even load the web page until the tab is selected.
Rather than needing to hotfix to remove/disable this on an ongoing basis, I wanted to include a command-line option to disable it quickly without modifying the source code.
pydm cli handling is kind of crude but this does work.
This involves a refactor to put the QWebEngineView widget on its own .ui file so that we can avoid importing …

MAINT/REF: isolate grafana log display and allow us to disable it

---

KFE_config.yml

chemRIXS vacuum PVs are going to be using CRIXS as a preface now, rather than CRIX. This will apply to CRIXS VAC PMPS PVs as well:

MAINT: Change chemRIXS vac PMPS PVs to now use CRIXS preface

---

.gitignore
nfs_afs_sync.sh

The intention is to point a cron job to the deployed version of this script to keep ACR updated when we update the LFE/KFE configurations, so that when this UI is opened in ACR (without tunneling) the configuration is maximally up-to-date.
I've opted not to sync the random svg files and other junk that has accumulated in the deployed folder.

ENH: add script for synchronizing pmps-ui with ACR

---

nfs_afs_sync.sh
sync_cron.sh

- script is easier to read now
- second script is used to manage stdout/stderr/logfile
- a cron daemon email is only sent on failure since only stderr makes it to terminal now

ENH: improve the ACR sync cron QOL

---

.flake8
KFE_config.yml
LFE_config.yml
TST_config.yml
arbiter_outputs.py
arbiter_outputs.ui
beamclass_table.py
beamclass_table.ui
grafana_log_display.py
line_beam_parameters.py
line_beam_parameters.ui
plc_ioc_status.py
pmps.py
pmps.ui
preemptive_requests.py
preemptive_requests.ui
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui
tooltips.py
utils.py

This is deployed as-is for `lpmps` and `kpmps`. `kpmps` isn't quite ready yet for the new PVs.
Some of the code is a little messy, sorry about that.
Big ideas:
- Now supports the superconducting "beam class" concept where applicable.
- Now has three modes: "NC" mode, "SC" mode, and "Both" mode to reduce clutter. The "Auto" mode will pick NC or SC depending on what the PV says, or both if the PV is disconnected.
- Added a beam class tab that shows all the beam class definitions.
- Added tooltips for eV ranges and beamclasses to help understand what is being done.
- Various logic and layout fixes.
Original to-do list:
And maybe more?

ENH: updates for SC

---

beamclass_table.py
line_beam_parameters.py

It's been confirmed that the "Spare" states will behave the same as "Unlimited", so we've decided to mark them as "Unlimited" so that "Spare" never appears in a readback and confuses somebody.

ENH: replace spare with unlimited for clarity based on known behavior

---

beamclass_table.py
tooltips.py

Handles a tooltip edge case when an invalid beam class is selected
So instead of crashing the tooltip it says something like "beamclass 1342 - Invalid - ? ? ? ? ? ? "
This has been live for a couple weeks

ENH: handle invalid beam classes in tooltip

---

KFE_config.yml
LFE_config.yml
TST_config.yml
beamclass_table.py
beamclass_table.ui
line_beam_parameters.py
line_beam_parameters.ui
pmps.py
pmps.ui
preemptive_requests.py
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui
utils.py
widgets.py

- PV name needed to change because it was too long (limit 60 chars)
- Some IOCs are updated, some are not
- I want the ui to work regardless, so let's make both versions work
This ended up having some cascading buggy behavior. The best way to resolve this was to refactor and clean up a lot of the eV range handling, doing it via widget promotion instead of by ad-hoc function applications.
Later, I was asked to make some adjustments to the beamclass table in the PMPS WG meeting e.g. citing the source and adding table header tooltips.

MAINT: backwards compatibility utils for PV name change

---

KFE_config.yml

- tmo motion is configured for 200 FFs now (currently has 89, will soon eclipse 100)
- KFE vac PLC was entirely missing from the pre-emptive section
I don't know who I should be asking to review PRs like these

FIX/ENH: KFE configs

---

KFE_config.yml
LFE_config.yml
TST_config.yml
grafana_log_display.py
line_beam_parameters.py
line_beam_parameters.ui
pmps.py
pmps.ui
preemptive_requests.py
single_tab.py
templates/preemptive_requests_entry.ui
templates/preemptive_requests_header.ui
trans_override.py
trans_override.ui

This PR is a companion to https://github.com/pcdshub/lcls-plc-kfe-arbiter/pull/20
In that PR, Maggie adds code and PVs for a user "Judgement Factor" that essentially acts as a PMPS transmission override.
This PR uses those PVs to:
- Add a section to the line_beam_parameters tab for setting transmission overrides
- Act as a middleman for transmission read/write so that this still works as expected
- Add a column to the pre-emptive requests tab that acts as the "adjusted" effective transmission values.
I feel pretty good about most of it.
The transmission read/write feels somewhat janky to me. I cannot (should not) make the UI write to PVs unprompted, so I think this is the best I can do in the python layer without creating horrors, but it still feels a bit off.
Updated pre-emptive requests …

ENH: transmission override ui elements

---

KFE_config.yml
LFE_config.yml
arbiter_outputs.py
fast_faults.py
fast_faults.ui
plc_ioc_status.py
templates/arbiter_outputs_entry.py
templates/arbiter_outputs_entry.ui
templates/arbiter_outputs_header.ui
templates/fastfaults_entry.ui
templates/fastfaults_header.ui
utils.py
widgets.py

- Add filterable veto indicators to the Fast Faults tab
- Add veto indicators, veto conditions, and fault counters to the Arbiter Outputs tab.
- Remove redundant on-destroy cleanup steps (pydm handles this adequately by default)
There's going to need to be a follow-up for figuring out how to get vetoes onto the Preemptive Requests page. These mostly match their associated FFHWOs but have some exceptions and don't self-report the vetoes.

ENH: FF/FFO Veto Visualizations

---

LFE_config.yml

Removing TXI from PMPS UI for now
-  Vetos aren't yet set for VAC & Motion PLCs 
-  It's not active also from ACR side

Removing TXI from PMPS UI for now - faults/vetos aren't set/active yet

---

docs/pre-release-notes.sh
docs/release_notes.py
docs/source/index.rst
docs/source/upcoming_changes.rst
docs/source/upcoming_release_notes/107-doc_doc.rst
docs/source/upcoming_release_notes/template-full.rst
docs/source/upcoming_release_notes/template-short.rst

Adds pre-release notes stuff to the docs folder
I selfishly like doing pre-release notes so my name goes places.  Also it feels weird to not have them at this point
Maybe I'll also add some actual contents to the docs page...
I did a `make html` once
This is docs, but also this PR

DOC: add pre-release notes framework to docs

---

docs/source/index.rst
docs/source/releases.rst

Release notes for v1.1.0
We should do real release notes!  
Interestingly, git detected the deletion of the pre-release notes and addition of release.rst as the movement of the file, since they were nearly identical
make html
this is docs

REL/DOC: release notes v1.1.0

---

README.md
docs/source/upcoming_release_notes/115-misc.rst
launch.sh
pmps.py
pmpsui/main.py
pmpsui/pmps.py

- Remove the symbolic link to the ui in the root of the repo because it doesn't work very well (no splash screen) and the vestigial `launch.sh` file that used it. Now there is one normal sanctioned way to launch the GUI (instead of at least three).
- Fix an issue where --no-web didn't work from the entrypoint (closes #113)
- Fix an issue where the pydm main window appeared too early (closes #114)
- Allow us to no longer pass pydm macros manually from the entrypoint (closes #104)
Some nitpicks found while deploying the splash screen and recent updates to prod.
It's now possible/preferable to launch the app using:
```
python -m pmpsui --area LFE --no-web
```
Interactively only
PR text, pre-release notes, readme

MNT: minor fixes
